"""Single-user login for the web UI and JSON API.

Everything except a short public allow-list requires a session cookie issued
by POST /login. Design notes:

* The password is never stored, only a salted PBKDF2-SHA256 hash
  (`ADMIN_PASSWORD_HASH` in .env, generated by `scripts/set_admin_password.py`).
* The session cookie is `<expiry>.<hmac>` signed with `SESSION_SECRET` *and*
  the password hash, so changing the password logs out every session.
* No password configured → private routes stay locked (fail closed).
* Failed logins are throttled per client IP.

Pure functions with an injectable clock so the rules are unit-testable.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import secrets
import time
from collections.abc import Callable

COOKIE_NAME = "pa_session"
SESSION_TTL_SECONDS = 30 * 24 * 3600
PBKDF2_ITERATIONS = 600_000

# Reachable without a session:
#   /healthz        — uptime-kuma + the CI smoke test
#   /reauth*        — Google OAuth; protected by REAUTH_SECRET and the OAuth state
#   /whatsapp/*     — called by the host-level bridge on 127.0.0.1:8000, and
#                     blocked at nginx so the internet can't reach it
#   /login, /logout, /favicon.svg
PUBLIC_EXACT = frozenset({"/healthz", "/login", "/logout", "/favicon.svg", "/reauth", "/reauth/callback"})
PUBLIC_PREFIXES = ("/whatsapp/",)


def is_public(path: str) -> bool:
    return path in PUBLIC_EXACT or path.startswith(PUBLIC_PREFIXES)


# --- password hashing -------------------------------------------------------

def _b64(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).rstrip(b"=").decode()


def _unb64(text: str) -> bytes:
    return base64.urlsafe_b64decode(text + "=" * (-len(text) % 4))


def hash_password(password: str, *, iterations: int = PBKDF2_ITERATIONS, salt: bytes | None = None) -> str:
    salt = salt or secrets.token_bytes(16)
    digest = hashlib.pbkdf2_hmac("sha256", password.encode(), salt, iterations)
    return f"pbkdf2_sha256:{iterations}:{_b64(salt)}:{_b64(digest)}"


def verify_password(password: str, encoded: str) -> bool:
    try:
        algo, iterations, salt, expected = encoded.split(":")
        if algo != "pbkdf2_sha256":
            return False
        digest = hashlib.pbkdf2_hmac("sha256", password.encode(), _unb64(salt), int(iterations))
    except (ValueError, TypeError):
        return False
    return hmac.compare_digest(_b64(digest), expected)


# --- session tokens ---------------------------------------------------------

def _signature(expires: int, secret: str, password_hash: str) -> str:
    key = f"{secret}\x00{password_hash}".encode()
    return _b64(hmac.new(key, f"v1:{expires}".encode(), hashlib.sha256).digest())


def make_session_token(secret: str, password_hash: str, *, now: float | None = None) -> str:
    expires = int((time.time() if now is None else now) + SESSION_TTL_SECONDS)
    return f"{expires}.{_signature(expires, secret, password_hash)}"


def verify_session_token(token: str | None, secret: str, password_hash: str, *, now: float | None = None) -> bool:
    if not token or not secret or not password_hash:
        return False
    expires_str, _, sig = token.partition(".")
    try:
        expires = int(expires_str)
    except ValueError:
        return False
    if expires < (time.time() if now is None else now):
        return False
    return hmac.compare_digest(sig, _signature(expires, secret, password_hash))


def safe_next(target: str | None) -> str:
    """Only allow same-site relative redirects after login (no open redirect)."""
    if target and target.startswith("/") and not target.startswith("//") and "\\" not in target:
        return target
    return "/settings"


# --- brute-force throttle ---------------------------------------------------

class LoginThrottle:
    """Lock an IP out after `max_failures` failed logins within `window` seconds."""

    def __init__(self, max_failures: int = 5, window: float = 900, clock: Callable[[], float] = time.time):
        self.max_failures, self.window, self.clock = max_failures, window, clock
        self._failures: dict[str, list[float]] = {}

    def _recent(self, ip: str) -> list[float]:
        cutoff = self.clock() - self.window
        recent = [t for t in self._failures.get(ip, []) if t > cutoff]
        if recent:
            self._failures[ip] = recent
        else:
            self._failures.pop(ip, None)
        return recent

    def is_locked(self, ip: str) -> bool:
        return len(self._recent(ip)) >= self.max_failures

    def record_failure(self, ip: str) -> None:
        self._failures.setdefault(ip, []).append(self.clock())

    def reset(self, ip: str) -> None:
        self._failures.pop(ip, None)
